//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtorsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListingPayment()
        {
            this.Listings = new HashSet<Listing>();
        }
    
        public int PaymentID { get; set; }
        public int ListingID { get; set; }
        public int ListingTypeID { get; set; }
        public int DurationDays { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal PricePerDay { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Listing> Listings { get; set; }
        public virtual Listing Listing { get; set; }
        public virtual ListingType ListingType { get; set; }
    }
}
