//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtorsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listing()
        {
            this.Contacts = new HashSet<Contact>();
            this.Favourites = new HashSet<Favourite>();
            this.ListingPayments = new HashSet<ListingPayment>();
        }
    
        public int ListingID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ListingType { get; set; }
        public string ListingStatus { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<System.DateTime> ExpireAt { get; set; }
        public int CustomerID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> BoostCount { get; set; }
        public Nullable<int> ListingTypeID { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite> Favourites { get; set; }
        public virtual ListingType ListingType1 { get; set; }
        public virtual Package Package { get; set; }
        public virtual ListingPayment ListingPayment { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingPayment> ListingPayments { get; set; }
    }
}
