//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtorsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListingType()
        {
            this.Listings = new HashSet<Listing>();
            this.ListingPayments = new HashSet<ListingPayment>();
        }
    
        public int ListingTypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> Multiplier { get; set; }
        public decimal BasePrice { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Listing> Listings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingPayment> ListingPayments { get; set; }
    }
}
