//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public int PaymentID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public decimal TotalAmount { get; set; }
        public string FilePath { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
