//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listing()
        {
            this.BoostHistories = new HashSet<BoostHistory>();
            this.Contacts = new HashSet<Contact>();
            this.FavoriteListings = new HashSet<FavoriteListing>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int ListingID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int PropertyID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> BoostCount { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ApprovalNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoostHistory> BoostHistories { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteListing> FavoriteListings { get; set; }
        public virtual Package Package { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
