//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdstest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageCustomer
    {
        public int EmployeeID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
