//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int PaymentID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> ListingID { get; set; }
        public int PackageID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> DurationDays { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Listing Listing { get; set; }
        public virtual Package Package { get; set; }
    }
}
