//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLog
    {
        public int LogId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string LogType { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
