//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int TransactionId { get; set; }
        public int PaymentId { get; set; }
        public string ActionType { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
        public string RawResponse { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
