//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImage
    {
        public int ImageID { get; set; }
        public int PropertyID { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string Caption { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
