//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public int PropertyDetailID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public Nullable<int> Bathrooms { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<decimal> FrontWidth { get; set; }
        public string Direction { get; set; }
        public string Furniture { get; set; }
        public Nullable<bool> HasBalcony { get; set; }
        public Nullable<bool> HasGarage { get; set; }
        public Nullable<bool> HasGarden { get; set; }
        public Nullable<bool> HasElevator { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
