//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdstest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Image
    {
        public int ImageID { get; set; }
        public int PropertyID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
