using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Realtors_Portal.Models;

namespace Realtors_Portal.Areas.Admin.Controllers
{
    public class ListingsController : Controller
    {
        private RealtorsPortalEntities db = new RealtorsPortalEntities();

        //Hiện các tin chờ duyệt
        //Author: Le Quang Dung
        public ActionResult PendingListing()
        {
            //Kiểm tra login
            var checkLogin = CheckLogin();
            if (checkLogin != null)
            {
                return checkLogin;
            }

            //Lấy danh sách listing chờ duyệt từ db
            var listings = db.Listings.Include(l => l.Customer)
                                      .Include(l => l.Package)
                                      .Where(l => l.Status == "Pending")
                                      .ToList();
            return View(listings);
        }

        //Duyệt tin
        //Author: Le Quang Dung
        public ActionResult ChangeStatus(int? id)
        {
            //Kiểm tra login
            var checkLogin = CheckLogin();
            if (checkLogin != null)
            {
                return checkLogin;
            }

            //Kiểm tra tồn tại của listing
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }

            return View(listing);
        }
        [HttpPost]
        public ActionResult ChangeStatus(int? id, string Status, string ApprovalNote)
        {
            try
            {
                //Lấy UserID từ session
                int UserID = Convert.ToInt32(Session["UserID"]);

                //Kiểm tra tồn tại của Listing
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Listing listing = db.Listings.Find(id);
                if (listing == null)
                {
                    return HttpNotFound();
                }

                //Tìm EmployeeID theo UserID
                var employee = db.Employees.FirstOrDefault(e => e.UserID == UserID);
                if (employee == null)
                {
                    ViewBag.Error = "Không có nhân viên này trong Employee";
                    return View();
                }

                //Thay đổi dữ liệu của listing
                listing.Status = Status;
                listing.ApprovedAt = DateTime.Now;
                listing.EmployeeID = employee.EmployeeID;
                listing.ApprovalNote = ApprovalNote;
                db.Entry(listing).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("PendingListing");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.InnerException.InnerException.Message;
                return View();
            }
        }

        //Kiểm tra login
        //Author: le Quang Dung
        private ActionResult CheckLogin()
        {
            //Kiểm tra đăng nhập hay chưa
            if (Session["UserID"] != null)
            {
                //Chuyển UserID trong session sang int
                bool parse = int.TryParse(Session["UserID"].ToString(), out int UserID);
                if (!parse)
                {
                    return RedirectToAction("Login", "UserAccounts", new { area = "" });
                }
                //Tìm kiếm user trong UserAccounts
                UserAccount user = db.UserAccounts.Where(u => u.UserID == UserID).FirstOrDefault();
                if (user == null)
                {
                    return RedirectToAction("Login", "UserAccounts", new { area = "" });
                }
                //Chuyển hướng
                if (user.Role == "Admin" || user.Role == "Employee")
                {
                    //Admin và Employee thì tiếp tục
                    return null;
                }
                else if (user.Role == "Agent" || user.Role == "Customer")
                {
                    //Agent và Customer vào giao diện Customer
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
            }
            return RedirectToAction("Login", "UserAccounts", new { area = "" });
        }
        //============================= Auto-generated by Entity Framework =====================================

        // GET: Admin/Listings
        public ActionResult Index()
        {
            var listings = db.Listings.Include(l => l.Category).Include(l => l.Customer).Include(l => l.Employee).Include(l => l.Package).Include(l => l.Property);
            return View(listings.ToList());
        }

        // GET: Admin/Listings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            return View(listing);
        }

        // GET: Admin/Listings/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName");
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName");
            ViewBag.PackageID = new SelectList(db.Packages, "PackageID", "PackageName");
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "Title");
            return View();
        }

        // POST: Admin/Listings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ListingID,CustomerID,PackageID,CategoryID,PropertyID,Title,Description,Price,Location,CreatedAt,ApprovedAt,ExpirationDate,Status,ViewCount,BoostCount,IsFeatured,EmployeeID,ApprovalNote")] Listing listing)
        {
            if (ModelState.IsValid)
            {
                db.Listings.Add(listing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", listing.CategoryID);
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName", listing.CustomerID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", listing.EmployeeID);
            ViewBag.PackageID = new SelectList(db.Packages, "PackageID", "PackageName", listing.PackageID);
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "Title", listing.PropertyID);
            return View(listing);
        }

        // GET: Admin/Listings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", listing.CategoryID);
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName", listing.CustomerID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", listing.EmployeeID);
            ViewBag.PackageID = new SelectList(db.Packages, "PackageID", "PackageName", listing.PackageID);
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "Title", listing.PropertyID);
            return View(listing);
        }

        // POST: Admin/Listings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ListingID,CustomerID,PackageID,CategoryID,PropertyID,Title,Description,Price,Location,CreatedAt,ApprovedAt,ExpirationDate,Status,ViewCount,BoostCount,IsFeatured,EmployeeID,ApprovalNote")] Listing listing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(listing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", listing.CategoryID);
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName", listing.CustomerID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", listing.EmployeeID);
            ViewBag.PackageID = new SelectList(db.Packages, "PackageID", "PackageName", listing.PackageID);
            ViewBag.PropertyID = new SelectList(db.Properties, "PropertyID", "Title", listing.PropertyID);
            return View(listing);
        }

        // GET: Admin/Listings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            return View(listing);
        }

        // POST: Admin/Listings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Listing listing = db.Listings.Find(id);
            db.Listings.Remove(listing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
